### ISSUE TITLE
to 5.6 or 5.3 ?

### ISSUE THREAD

**Issue by docteurklein** [jaytaph/Transphpile#2]
In your description, you say the target is 5.6,
but the title in the README says 5.3.
What is the target?

BTW, nice idea of you!

**Comment by jaytaph** [comment]
The idea is to transpile to 5.3 (mostly because there are still (too) many systems running on 5.3.x, (don't ask!))..   However, transpiling every php 5.4,5.5,5.6 and 7.0 feature back is a bit too difficult (for instance, generators and such).

So.. Our direct goal is PHP5.6, and hopefully we can transpile back most things to php5.5. As said in issue #1, if that is not possible we could add warnings. Most generated transpiled code though is based on php 5.3.

I probably would need to change the readme and setup some (decent) documentation on it to make the goals more consistent :)
